/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.vitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createJPanel
     */
    private Application application;
    public CreateJPanel() {
        initComponents();
    }

    CreateJPanel(Application application) {
        initComponents();
        this.application = application;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldObservationId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldBloodPressure = new javax.swing.JTextField();
        fieldTemperature = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addObservationBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Create a vital sign ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));
        add(fieldObservationId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 20, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("BLOOD PRESSURE");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 30));
        add(fieldBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, 30));
        add(fieldTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("TEMPERATURE");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 30));

        addObservationBtn.setBackground(new java.awt.Color(51, 153, 255));
        addObservationBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addObservationBtn.setText("ADD OBSERVATION");
        addObservationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObservationBtnActionPerformed(evt);
            }
        });
        add(addObservationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addObservationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObservationBtnActionPerformed
        // TODO add your handling code here:
        //add an observation to vital sign history
        vitalSignHistory history = this.application.getHistory();
        String id = fieldObservationId.getText();
        String temperature = fieldTemperature.getText();
        String bloodPressure = fieldBloodPressure.getText();
        history.createObservation(Integer.valueOf(id), Double.valueOf(temperature), Double.valueOf(bloodPressure));
        JOptionPane.showMessageDialog(null, "Added Observation");
    }//GEN-LAST:event_addObservationBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addObservationBtn;
    private javax.swing.JTextField fieldBloodPressure;
    private javax.swing.JTextField fieldObservationId;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
